//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUOTATION.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOTATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUOTATION()
        {
            this.QUOTATION_EQUIPMENT = new HashSet<QUOTATION_EQUIPMENT>();
            this.QUOTATION_NOTE = new HashSet<QUOTATION_NOTE>();
        }
    
        public int AUTO_ID { get; set; }
        public string NO { get; set; }
        public Nullable<int> TYPE { get; set; }
        public decimal BOSS_RATE { get; set; }
        public int BOSS_SHIFT_1 { get; set; }
        public int BOSS_SHIFT_2 { get; set; }
        public decimal GUARD_MAN_RATE { get; set; }
        public int GUARD_MAN_SHIFT_1 { get; set; }
        public int GUARD_MAN_SHIFT_2 { get; set; }
        public decimal GUARD_WOMAN_RATE { get; set; }
        public int GUARD_WOMAN_SHIFT_1 { get; set; }
        public int GUARD_WOMAN_SHIFT_2 { get; set; }
        public Nullable<decimal> BAIL_RATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public int CONTACT_ID { get; set; }
        public int SALE_OFFICE_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public string CRATE_BY { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        public virtual CUSTOMER_CONTACT CUSTOMER_CONTACT { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUOTATION_EQUIPMENT> QUOTATION_EQUIPMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUOTATION_NOTE> QUOTATION_NOTE { get; set; }
        public virtual SALE_OFFICE SALE_OFFICE { get; set; }
    }
}
